
@startuml State Diagram (複数)

note "「」括弧はボタンを表している" as n

[*] --> 初期状態 : アプリ起動

初期状態 --> 追加中 : 「アラームを追加+」

state 初期状態 {
    初期状態 : アラームは０件で「追加ボタン+」のみ
}

追加中 --> 一覧表示 : 「保存」

追加中 --> 初期状態 : 「キャンセル」

追加中 --> 一覧表示 : 「キャンセル」

一覧表示 --> 追加中 : 「アラームを追加+」※すでに５件ある場合は押下できない

一覧表示 --> 鳴動中 : 設定時刻になると音がなる

一覧表示 --> 選択中 : アラーム行押下

state 一覧表示 {
    一覧表示 : 新規追加・編集後・ON切替でON (起動状態)
    一覧表示 : 鳴動後・OFF切替でOFF (停止状態)
}

鳴動中 --> 一覧表示 : 「停止」で音を止める

選択中 --> 選択中 : アラーム行押下

選択中 --> 編集中 : 「編集」※1件選択中の場合のみ

選択中 --> 一覧表示 : 「一括解除」

選択中 --> 一覧表示 : 「一括削除」

選択中 --> 初期状態 : 「一括削除」 ※アラーム０件

編集中 --> 一覧表示 : 「保存」

編集中 --> 選択中 : 「キャンセル」

@enduml