@startuml State Transition Diagram

[*] --> 初期状態 : アプリ起動

state 初期状態 {
    初期状態 : タイトル名
    初期状態 : 追加ボタン： 表示
    初期状態 : 削除ボタン： 非表示
    初期状態 : ※初期アラームなどは設定されていない状態とする
}

初期状態 --> アラーム追加画面 : **アラームを追加+**ボタン押下

state アラーム追加画面 {
    アラーム追加画面 : 時間設定 : 00~23
    アラーム追加画面 : 分設定 : 00~59
    アラーム追加画面 : 保存ボタン : 表示
    アラーム追加画面 : キャンセルボタン : 表示
}

' note left of アラーム追加画面
' ➖設定項目➖
' **秒**単位以下は不可
' ' ◉「保存」ボタン押下による、
' ' すでに設定されている時刻の**アラーム同時刻設定不可**
' end note

アラーム追加画面 --> アラーム一覧画面 : **保存**ボタン押下
アラーム一覧画面 --> アラーム追加画面 : **アラームを追加+**ボタン押下
' アラーム一覧画面 --> 初期状態

state アラーム一覧画面 {
アラーム一覧画面 : 設定アラーム１行(ON状態)
アラーム一覧画面 : ON・OFF切替ボタン : 表示
アラーム一覧画面 : 「アラームを追加+」 : 表示
アラーム一覧画面 : 編集ボタン : 非表示(アラーム選択後: 表示)
アラーム一覧画面 : 一括解除ボタン : 非表示(アラーム選択後: 表示)
アラーム一覧画面 : 削除ボタン : 非表示(アラーム選択後: 表示)
}

' note on link
' 設定したアラームが0個になると
' 初期状態に遷移する
' end note

' note left of アラーム一覧画面
' ➖操作項目➖
' ◉ アラーム初期状態: ON
' ◉ アラーム複数選択 : 可能
' ' ◉ **5つ**までアラームを記憶できる ⇒ **ローカルストレージ**を利用

' ※設定したアラームが0個になると
' **初期状態**に遷移する
' end note

アラーム一覧画面 --> アラーム一覧画面 : **削除ボタン**押下
アラーム一覧画面 --> 初期状態 : 設定したアラームが0個になると**初期状態**に遷移する
アラーム一覧画面 --> アラーム編集画面 : **編集ボタン**押下
アラーム編集画面 --> アラーム一覧画面 : **保存ボタン**押下

state アラーム編集画面 {
    アラーム編集画面 : 時間設定 : 00~23
    アラーム編集画面 : 分設定 : 00~59
    アラーム編集画面 : 保存ボタン : 表示
    アラーム編集画面 : キャンセルボタン : 表示
}

アラーム一覧画面 -[dotted]-> 内部状態 : 初期状態はONなので**アラームON**へ
内部状態 -[dotted]-> アラーム一覧画面
' note on link
' 「アラームON・OFF」は「アラーム一覧画面」の
' 内部状態なのでドット矢印で表示
' end note
state 内部状態 {
    state アラームON: 設定アラーム１行(ON状態)
    state アラームOFF: 設定アラーム１行(OFF状態)

    アラームON --> アラームOFF : ON・OFF切替(OFF切替)
    アラームOFF --> アラームON : ON・OFF切替(ON切替)
}

アラームON --> アラーム鳴動 : 設定時刻になると音を鳴らす
アラーム鳴動 --> アラームOFF : **停止ボタン**押下で音を止める

state アラーム鳴動 {
    アラーム鳴動 : ダイアログボックス : 表示
    アラーム鳴動 : 停止ボタン : 表示
}

' note right of アラーム鳴動
' ➖鳴動条件➖
' ◉ 端末の音量が0またはスリープ状態の場合、
' 音は**鳴らない**
' ◉ 機内モード時(Wi-FiやBluetoothのoff時)は音は**鳴る**
' end note

@enduml