@startuml State Diagram (単体)

[*] --> 初期状態 : アプリ起動

初期状態 --> アラーム起動 : アラーム設定

アラーム起動 --> アラーム停止 : ON・OFF切替(OFF切替)

アラーム停止 --> アラーム起動 : ON・OFF切替(ON切替)

アラーム起動 --> 鳴動中 : 設定時刻になると音を鳴らす

鳴動中 --> アラーム停止 : 停止ボタン押下で音を止める

アラーム起動 --> 初期状態 : アラーム削除で０件

アラーム停止 --> 初期状態 : アラーム削除で０件

@enduml