
@startuml timer-uml

actor User
boundary UI
participant Timer
participant Ticker
participant GenericDisplay

== 時間設定 ==
User -> UI:時間を設定(hh:mm:ss)
UI -> UI:hh:mm:ss -> seconds(秒)に変換
UI -> Timer:setTime(seconds)

== 開始 ==
User -> UI:開始ボタン押下
UI -> Timer:start()

alt duration == 0
    Timer ->Display:showError()
else duration > 0
    Timer -> Ticker:startTicking()
    Timer -> Display:formatTime(remainingTime)
end

== カウントダウン ==
loop every 1 seconds
    Ticker -> Timer:tick()
    Timer -> Display:formatTime(remainingTime)
end
@enduml
