@startuml timer-uml

[*] --> 初期状態


初期状態 --> 設定完了 : 時間設定


設定完了 --> カウントダウン中 : 開始ボタン押下


カウントダウン中 --> 一時停止中  : 一時停止ボタン押下


一時停止中 --> カウントダウン中 : 再開ボタン押下


カウントダウン中 --> 終了 : 残り時間が0になる


終了 --> 設定完了 : 停止/リセットボタン押下


カウントダウン中 --> 設定完了 : リセットボタン押下


一時停止中 --> 設定完了 : リセットボタン押下


@enduml