


@startuml timer-uml

class Timer {
    -state:TimerState
    -remainingTime:number
    -duration:number
    +start():void
    +stop():void
    +pause():void
    +reset():void
    -tick():void
    +cancel():void
    +setTime(seconds:number):void
}

interface Display {
    +formatTime(time:number):string
    +showError():void
}

class TimerDisplay {
    -element:HTMLElement
    +formatTime(time:number):string
    +showError():void
}

class Ticker {
    +startTicking():void
    +stopTicking():void
}

enum TimerState {
    Ready
    Running
    Paused
    Finished
    Error
}

Timer --> Display
Timer --> Ticker
Timer --> TimerState
Display <|.. TimerDisplay


@enduml